%YAML:1.0
#Rotation from laser frame to imu frame, imu^R_laser
extrinsicRotation_imu_laser: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [-1, 0, 0,
          0, 1, 0,
          0, 0, -1]
#Translation from laser frame to imu frame, imu^T_laser
extrinsicTranslation_imu_laser: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [0.0, 0.0, 0.0]


#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation_imu_camera: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [0.0,  0.0,  -1,
         -1,  0.0, 0.0,
         0.0, 1,  0.0]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation_imu_camera: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [0.006422381632411965, 0.019939800449065116, 0.03364235163589248]


#Rotation from laser frame to camera frame, camera^R_laser
extrinsicRotation_camera_laser: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [0,  -1,  0,
          0,  0,  -1,
         1,  0,  0]
#Translation from laser frame to camera frame, camera^T_laser
extrinsicTranslation_camera_laser: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [ 0, -0.03, 0]